port: ":8001"

mongo:
    uri: "mongodb://localhost:27017"
    name: "testdb"
    userCollection: "users"
    projectCollection: "projects"
    boardCollection: "boards"
    taskListCollection: "taskLists"
    taskCollection: "tasks"
    tokenCollection: "tokenOut"