port: ":8001"

mongo:
    uri: ""
    name: "testdb"
    userCollection: "users"
    projectCollection: "projects"
    projectUser: "projects"
    boardCollection: "boards"
    taskListCollection: "taskLists"
    taskCollection: "tasks"