version: "3.8"
services:
  redis:
    image: redis:latest
    restart: always
    networks:
      - backend
    ports:
      - "6379"

  postgres:
    image: postgres:latest
    restart: always
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: yak
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    networks:
      - backend
    environment:
      PGADMIN_DEFAULT_EMAIL: yak@yak.ru
      PGADMIN_DEFAULT_PASSWORD: yak
    ports:
      - "80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./nginx/servers.json:/pgadmin4/servers.json

  fiber_main:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    networks:
      - backend
    ports:
      - "8001"
    depends_on:
      - redis
      - postgres
    volumes:
      - ./backend:/app

  fiber_ro1:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      YAK_READONLY: y
    networks:
      - backend
    ports:
      - "8001"
    depends_on:
      - redis
      - postgres
    volumes:
      - ./backend:/app

  fiber_ro2:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      YAK_READONLY: y
    networks:
      - backend
    ports:
      - "8001"
    depends_on:
      - redis
      - postgres
    volumes:
      - ./backend:/app

  svelte:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    networks:
      - frontend
    ports:
      - "5000"
    depends_on:
      - fiber_main
    volumes:
      - ./frontend:/app
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - fiber_main
      - svelte
    networks:
      - frontend
      - backend
    ports:
      - 443:443
      - 80:80

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend:
  frontend:
