name: run-tests
on: [push]
on:
pull_request:

env:
  GO_VERSION: 1.15

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: yak_test_real_db
        ports:
          - 5432/tcp

    steps:
    - name: set up go ${{env.GO_VERSION}}
      uses: actions/setup-go@v2
      with:
        go-version: ${{env.GO_VERSION}}
      id: go

    - name: before_script
      run: 
      - psql -c 'create database yak_test_real_db;' -U postgres
      - psql -d yak_test_real_db -c '\i backend/scripts/init.sql;' -U postgres

    - name: script
      run: 
      - cd backend
      - go test -short ./... # unit tests
      - go test -tags=integration ./... # integration tests
      # - go test -tags=e2e # e2e tests
      # - go test -tags=bdd_e2e # BDD e2e tests